version: '3'

dotenv: ['.env']

output: prefixed

silent: true

tasks:
  default:
    desc: Default task
    cmds:
      - task: run

  build:
    desc: Build the application
    cmds:
      - echo "compiling binary..."
      - CGO_ENABLED=0 go build -ldflags="{{.LDFLAGS}}" -o bin/helmes ./cmd/helmes
    vars:
      VERSION:
        sh: git rev-parse --short HEAD
      DATE:
        sh: date -u +%Y-%m-%d-%H:%M:%S-%Z
      LDFLAGS: "-X github.com/rugwirobaker/helmes.version={{.VERSION}} -X github.com/rugwirobaker/helmes.buildDate={{.DATE}}"
  
  generate:
    desc: Generate code
    cmds:
      - go generate ./...
   
  image:
    desc: Build the application container images
    cmds:
      - docker build --network host -t helmes:{{.GIT_COMMIT}} .
    vars:
      GIT_COMMIT:
        sh: git rev-parse --short HEAD

  run:
    desc: Start the application
    deps: [build]
    cmds:
      - ./bin/helmes
  
  test:
    desc: Run unit tests
    cmds:
      - go test -race -covermode=atomic ./...